Fe build image action
Byzanteam/jet-actions pull request #42
Opened 2022-12-07 04:40 UTC by moonRider

2022-12-07 04:42 UTC, moonRider commented
`build image` 这个 action 中 `get-app-info` 这个 step 我不想内置的，但是不知道外部怎么传不确定个数的参数，这个有办法么？@fahchen

2022-12-07 06:26 UTC, vanppo approved these changes
要不把 README 拆到各自的目录下面去吧 cc @fahchen

2022-12-07 06:30 UTC, fahchen commented on README.md
> +  uses: byzanteam/jet-actions/deploy@main
这个不应该打到这个 commit 里面

2022-12-07 06:30 UTC, fahchen commented on README.md
> +    file: package.json
```suggestion
    packageFile: package.json
```

2022-12-07 06:30 UTC, fahchen commented on README.md
> +    registry_password: ${{ secrets.GITHUB_TOKEN }}
还差一个参数 `context`，默认值是 `.`

2022-12-07 06:30 UTC, fahchen commented on fe-build-image/action.yml
> +    required: true
这两个合并成一个参数 tags 吧，不分开了
可以指定多个 tag

2022-12-07 06:30 UTC, fahchen commented on fe-build-image/action.yml
> +          APP_NAME=${{ inputs.app_name }}
`build-args` 也允许通过 `inputs` 传入过来一下，自带的是这两个，还允许其他的

2022-12-07 06:58 UTC, moonRider commented on fe-build-image/action.yml
> +          APP_NAME=${{ inputs.app_name }}
这个我就是不知道怎么定义参数了，build-args 整体作为一个参数？用户怎么传递 object 的东西呢？

2022-12-07 07:21 UTC, fahchen commented on fe-build-image/action.yml
> +          APP_NAME=${{ inputs.app_name }}
```suggestion
        build-args: |
          APP_VSN=${{ inputs.app_version }}
          APP_NAME=${{ inputs.app_name }}
          ${{ inputs.build_args }}
```

2022-12-07 07:22 UTC, fahchen requested changes

2022-12-07 07:22 UTC, fahchen commented on README.md
> +## Fe Build Image ![Fe Build Image CI](https://github.com/Byzanteam/jet-actions/workflows/Fe%20build%20image%20CI/badge.svg)
你这个没有测试，就别加这个了
```suggestion
## Fe Build Image
```

2022-12-07 07:43 UTC, moonRider commented on fe-build-image/action.yml
> +          APP_NAME=${{ inputs.app_name }}
把 APP_VSN 和 APP_NAME 外置了，内部没有 get-app-info 这个步骤了。感觉放里面不合适

2022-12-07 08:00 UTC, fahchen requested changes

2022-12-07 08:00 UTC, fahchen commented on fe-build-image/action.yml
> +  docker_file:
dockerfile

2022-12-07 08:00 UTC, fahchen commented on README.md
> +    tag: Byzanteam/${{ steps.get-app-info.outputs.name }}:${{ steps.get-app-info.outputs.version }}
这里理解好像有点问题，image 由两部分组成 image_name:image_tag 组成，所以这里的 tag 包括了 name

https://docs.docker.com/engine/reference/commandline/tag

2022-12-07 08:00 UTC, fahchen commented on fe-get-app-info/action.yml
> +      id: get-app-version
如果获取不到的话，报一下错，这里我建议写成一个 ts 的 action 吧，这样你直接读取 json 文件就好了，不需要写脚本

2022-12-07 11:13 UTC, moonRider commented on README.md
> +    tag: Byzanteam/${{ steps.get-app-info.outputs.name }}:${{ steps.get-app-info.outputs.version }}
这里让用户传 tags，在内部定义 tags 有丢丢蛋疼

2022-12-08 02:10 UTC, vanppo commented on README.md
> +* [Deploy](https://github.com/Byzanteam/jet-actions/tree/main/deploy)
```suggestion
* [Deploy](/deploy)
```
用相对路径吧

2022-12-08 02:41 UTC, fahchen commented on fe-get-app-info/.prettierrc.json
> +}
这个文件需要吗？

2022-12-08 02:45 UTC, fahchen commented on fe-build-image/action.yml
> +          SOURCE_SHA=${{ github.sha }}
这两个变量更新到 scaffold 的 Dockerfile 里面一下

2022-12-08 02:45 UTC, fahchen commented on fe-build-image/README.md
> +      ghcr.io/Byzanteam/${{ steps.get-app-info.outputs.name }}:${{ steps.get-app-info.outputs.version }}
每次让他们填这个会不会比较蛋疼？

2022-12-08 02:45 UTC, fahchen commented on fe-build-image/README.md
> +    registry_password: ${{ secrets.GITHUB_TOKEN }}
这个要不也不填了吧，统一都到这些地方和地址，到时候我们要改成其他的 registry 就只需要到这里改一下就好了

2022-12-08 03:12 UTC, moonRider commented on fe-get-app-info/.prettierrc.json
> +}
需要吧，每个项目都要 prettier，我建了纯 js/ts 项目的模版issue，到时候里面都会有这些

2022-12-08 03:43 UTC, moonRider commented on fe-build-image/action.yml
> +          SOURCE_SHA=${{ github.sha }}
ok

2022-12-08 03:47 UTC, fahchen commented on fe-get-app-info/.prettierrc.json
> +}
这个不是集成到 eslint 里面去了吗？

2022-12-08 03:53 UTC, fahchen requested changes

2022-12-08 03:53 UTC, fahchen commented on fe-build-image/README.md
> +    registry_password: ${{ secrets.GITHUB_TOKEN }}
这几个参数做成不允许填写

2022-12-08 03:53 UTC, fahchen commented on fe-build-image/README.md
> +    scope: Byzanteam
这个也做成不允许填写

2022-12-08 03:53 UTC, fahchen commented on fe-build-image/action.yml
> +          SOURCE_SHA=${{ github.sha }}
PR 放这里

2022-12-08 04:50 UTC, moonRider commented on fe-build-image/action.yml
> +          SOURCE_SHA=${{ github.sha }}
https://github.com/Byzanteam/jet-scaffolds/pull/16

2022-12-08 04:52 UTC, fahchen approved these changes
整理下 commits 吧

2022-12-08 05:09 UTC, moonRider commented on fe-get-app-info/.prettierrc.json
> +}
文件要保留
1. eslint 集成的是 prettier/prettier 规则（prettier 的错误会统一报到 prettier/prettier 规则上)
2. prettierrc 会定义一些和 eslint 有冲突的规则（比如 semi，prettier 内默认是 true，导致 eslint 无论怎么定义 semi，都会按 prettier 的规则执行，我们期待 semi 是 false，没有这个文件定义就会报错）

2022-12-08 05:28 UTC, merged