Feat/yangke/preview
Byzanteam/jet-actions pull request #51
Opened 2023-03-16 11:36 UTC by YkeLit

前端预览

2023-03-16 11:56 UTC, fahchen requested changes

2023-03-16 11:56 UTC, fahchen commented on pr-preview/action.yml
> +        tags: registry.cn-hangzhou.aliyuncs.com/skylark/${{ steps.extract.outputs.app_name }}:${{ steps.extract.outputs.app_version }}
这个不放进来，这里 action 的输入就是 image 就好了吧

2023-03-17 06:22 UTC, YkeLit commented on pr-preview/action.yml
> +        tags: registry.cn-hangzhou.aliyuncs.com/skylark/${{ steps.extract.outputs.app_name }}:${{ steps.extract.outputs.app_version }}
改掉了

2023-03-20 10:11 UTC, fahchen commented on pr-preview/README.md
> +    image_tag: "1.0.0"
`image_tag` 这个例子不对，你是不是得包含完整的路径那些啊？

2023-03-21 01:38 UTC, YkeLit commented on pr-preview/README.md
> +    image_tag: "1.0.0"
完整路径应该是 是固定的吧，这个固定的应该在配置文件写一次就可以了

2023-05-17 10:07 UTC, closed without merging