chore: 自动升级 docker compose 部署的前端应用
Byzanteam/jet-actions pull request #53
Opened 2023-04-10 03:34 UTC by YkeLit

* 使用 shell 脚本获取当前服务器前端镜像的名称和信息
* 修改部署前端镜像的 docker-compose 文件
* 使用命令更新应用
> [测试 actions](https://github.com/Byzanteam/jet-autoflow-example/actions/runs/4654150372/jobs/8235680752)

2023-04-10 04:50 UTC, fahchen requested changes

2023-04-10 04:50 UTC, fahchen commented on compose-upgrade/action.yml
> +    default: 22
default 和 required 不会同时存在哈

2023-04-10 04:50 UTC, fahchen commented on compose-upgrade/action.yml
> +    required: true
这个叫 deploy to 不合适，因为你不是在部署是在更新，应该是指定一下 dovker-compose file 的位置

2023-04-10 04:50 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +	"sed -i \"s/$image/$INPUT_IMAGE_NAME:$INPUT_IMAGE_VERSION/\" $INPUT_DEPLOY_TO/docker-compose.yml"
如果一个 image 被使用了多次这里为什么要设计成修改 docker-compose 文件呢？

2023-04-10 06:37 UTC, YkeLit commented on compose-upgrade/entrypoint.sh
> +	"sed -i \"s/$image/$INPUT_IMAGE_NAME:$INPUT_IMAGE_VERSION/\" $INPUT_DEPLOY_TO/docker-compose.yml"
1. 现在前端镜像还没有遇到过同一服务器多次使用的情况
2. docker-compose 也不支持在命令行中设置 image tag 参数

2023-04-10 06:38 UTC, YkeLit commented on compose-upgrade/action.yml
> +    required: true
改成 upgrade_path 可以不呀

2023-04-10 06:48 UTC, fahchen commented on compose-upgrade/action.yml
> +    required: true
可以叫 docker_compose_file_path

2023-04-10 06:59 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +	"sed -i \"s/$image/$INPUT_IMAGE_NAME:$INPUT_IMAGE_VERSION/\" $INPUT_DEPLOY_TO/docker-compose.yml"
1. skylark 被用过多次，一个是 app 一个是 sidekiq，好像同时更新这两个问题不大？

2023-04-10 07:03 UTC, YkeLit commented on compose-upgrade/entrypoint.sh
> +	"sed -i \"s/$image/$INPUT_IMAGE_NAME:$INPUT_IMAGE_VERSION/\" $INPUT_DEPLOY_TO/docker-compose.yml"
在docker compose 中，更新 skylark 的方式通过服务器的脚本去更新的，后端不应该去使用这个 actions 去做更新吧

2023-04-10 07:59 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +	"sed -i \"s/$image/$INPUT_IMAGE_NAME:$INPUT_IMAGE_VERSION/\" $INPUT_DEPLOY_TO/docker-compose.yml"
在 readme 里面加一个说明

2023-04-10 08:01 UTC, fahchen commented on compose-upgrade/README.md
> +    docker_compose_file_path: /var/www
这路是 file path 不是 dir 哈

2023-04-11 05:51 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +	"docker-compose -f $INPUT_DOCKER_COMPOSE_FILE_PATH up -d"
1. 这里是不是设计成修改某个 service 的 image 值呀，就不用去查了
2. 可以打印一下更新前后的值到日志里面

2023-04-11 06:29 UTC, YkeLit commented on compose-upgrade/entrypoint.sh
> +	"docker-compose -f $INPUT_DOCKER_COMPOSE_FILE_PATH up -d"
在docker compose 的文档里没有找到有在命令行设置 image 值
  * [docker compose CLI](https://docs.docker.com/engine/reference/commandline/compose_up/)

2023-04-11 07:59 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +	"docker-compose -f $INPUT_DOCKER_COMPOSE_FILE_PATH up -d"
不是用 cli 工具去修改
下面是一个 `docker-compose.yaml` 文件，通过这个 action 去更新其中的一个 service 的 image 的值
比如：更新 foo 的 image 为 `foo:latest`，那么找到这 services.foo.image 这个路径的值进行修改
```yaml
services:
  foo:
    image: foo
  bar:
    image: bar
    profiles:
      - test
  baz:
    image: baz
    depends_on:
      - bar
    profiles:
      - test
  zot:
    image: zot
    depends_on:
      - bar
    profiles:
      - debug
```

2023-04-11 08:00 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +	"docker-compose -f $INPUT_DOCKER_COMPOSE_FILE_PATH up -d"
看看这个工具 https://github.com/mikefarah/yq

2023-04-11 08:43 UTC, fahchen commented on compose-upgrade/action.yml
> +    required: true
```suggestion
  service_name:
    description: service to be updated
    required: true
  image_tag:
    description: the image tag
    required: true
```

2023-04-12 03:59 UTC, fahchen requested changes

2023-04-12 03:59 UTC, fahchen commented on compose-upgrade/action.yml
> +  upgrade_user:
upgrade 的前缀有点多余，你这 action 已经说明了是 upgrade

2023-04-12 03:59 UTC, fahchen commented on compose-upgrade/action.yml
> +  upgrade_user:
可以改成 ssh_ 前缀，或者不要前缀

2023-04-12 03:59 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +	"yq -i '.services.$INPUT_SERVICE_NAME.image=\"$INPUT_IMAGE_TAG\"' $INPUT_DOCKER_COMPOSE_FILE_PATH"
不安装 yq 到 remote 上面行不，这样会污染 remote 的环境

2023-04-12 04:01 UTC, fahchen requested changes

2023-04-12 04:01 UTC, fahchen commented on compose-upgrade/README.md
> +> 注：此 actions 适用前端应用升级
这个注释没必要了

2023-04-12 04:01 UTC, fahchen commented on compose-upgrade/action.yml
> +    description: upgrade image name
描述有问题

2023-04-12 04:01 UTC, fahchen commented on compose-upgrade/action.yml
> +    description: upgrade image version
描述有问题

2023-04-12 04:23 UTC, YkeLit commented on compose-upgrade/entrypoint.sh
> +	"yq -i '.services.$INPUT_SERVICE_NAME.image=\"$INPUT_IMAGE_TAG\"' $INPUT_DOCKER_COMPOSE_FILE_PATH"
不得行哦，不然 remote 会提示找不到这个命令

2023-04-12 04:38 UTC, YkeLit commented on compose-upgrade/action.yml
> +  upgrade_user:
我把前缀去掉了

2023-04-12 04:38 UTC, YkeLit commented on compose-upgrade/entrypoint.sh
> +	"yq -i '.services.$INPUT_SERVICE_NAME.image=\"$INPUT_IMAGE_TAG\"' $INPUT_DOCKER_COMPOSE_FILE_PATH"
这个command 应该什么影响，毕竟他只是二进制文件也不提供服务也不消耗资源

2023-04-13 09:03 UTC, YkeLit commented
@fahchen 这个应该没什么问题了吧

2023-04-13 09:23 UTC, fahchen commented
![image](https://user-images.githubusercontent.com/855678/231715445-87c682bf-17ad-40f4-8b93-77576af70d23.png)
通过右侧那个按钮拉 review，不要用 at

2023-04-13 09:27 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +	"docker-compose -f $INPUT_DOCKER_COMPOSE_FILE_PATH up -d"
把 yq 安装在 action 里面然后再进行修改上传回去呢？
1. 安装 yq 到 action 里面（或者提供镜像）
2. 把 compose file 备份一下
3. 把 compose file copy 回来然后修改后传回去覆盖旧的文件
4. compose up

2023-04-13 09:28 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +	"yq -i '.services.$INPUT_SERVICE_NAME.image=\"$INPUT_IMAGE_TAG\"' $INPUT_DOCKER_COMPOSE_FILE_PATH"
还是有影响，我无缘无故多了一个包

2023-04-13 10:44 UTC, fahchen requested changes

2023-04-13 10:44 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +scp -P $INPUT_PORT -i $KEY_PATH -o StrictHostKeyChecking=no ./docker-compose.yml $INPUT_USER@$INPUT_HOST:$INPUT_DOCKER_COMPOSE_FILE_PATH
这些步骤都别存储到本地文件吧，在内存里面处理就好了

2023-04-13 11:51 UTC, YkeLit commented on compose-upgrade/entrypoint.sh
> +scp -P $INPUT_PORT -i $KEY_PATH -o StrictHostKeyChecking=no ./docker-compose.yml $INPUT_USER@$INPUT_HOST:$INPUT_DOCKER_COMPOSE_FILE_PATH
这个脚本本身是跑在 docker 容器中的，应该也不算本地吧

2023-04-13 13:09 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +scp -P $INPUT_PORT -i $KEY_PATH -o StrictHostKeyChecking=no ./docker-compose.yml $INPUT_USER@$INPUT_HOST:$INPUT_DOCKER_COMPOSE_FILE_PATH
1. 我们不知道 GitHub 怎么存储和管理镜像的文件系统的
2. 这里我们不把它搞到本地就行（你不要理解是在容器里面的，而是在一台服务器上）

2023-04-13 13:11 UTC, fahchen requested changes
给一个成功的演示

2023-04-13 13:11 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +	"cp $INPUT_DOCKER_COMPOSE_FILE_PATH $INPUT_DOCKER_COMPOSE_FILE_PATH.bak"
给一个时间戳在这里吧（后面可以考虑把是否备份做成一个参数来控制，比如指定一个备份文件夹）
```suggestion
	"cp $INPUT_DOCKER_COMPOSE_FILE_PATH $INPUT_DOCKER_COMPOSE_FILE_PATH.${date}.bak"
```

2023-04-13 15:23 UTC, YkeLit commented on compose-upgrade/entrypoint.sh
> +	"cp $INPUT_DOCKER_COMPOSE_FILE_PATH $INPUT_DOCKER_COMPOSE_FILE_PATH.bak"
好的，可以的

2023-04-13 15:42 UTC, fahchen requested changes

2023-04-13 15:42 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +	"cp $INPUT_DOCKER_COMPOSE_FILE_PATH $INPUT_DOCKER_COMPOSE_FILE_PATH.`date`.bak"
不是，你别直接把 date 往上扔啊，格式化一下

2023-04-13 15:49 UTC, YkeLit commented on compose-upgrade/entrypoint.sh
> +	"cp $INPUT_DOCKER_COMPOSE_FILE_PATH $INPUT_DOCKER_COMPOSE_FILE_PATH.`date`.bak"
https://github.com/Byzanteam/jet-autoflow-example/actions/runs/4691007166/jobs/8315353208
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/48484963/231814803-9abf941e-49da-4388-8478-34c01aa4f46f.png">

2023-04-13 15:55 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +	"cp $INPUT_DOCKER_COMPOSE_FILE_PATH $INPUT_DOCKER_COMPOSE_FILE_PATH.`date`.bak"
中间一般不打分隔符

2023-04-13 16:06 UTC, YkeLit commented on compose-upgrade/entrypoint.sh
> +	"cp $INPUT_DOCKER_COMPOSE_FILE_PATH $INPUT_DOCKER_COMPOSE_FILE_PATH.`date`.bak"
以 `. ` 分隔，这个应该是可以的

2023-04-14 00:16 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +	"cp $INPUT_DOCKER_COMPOSE_FILE_PATH $INPUT_DOCKER_COMPOSE_FILE_PATH.`date`.bak"
没必要，一般不打分隔符

2023-04-14 01:36 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +		"tee $INPUT_DOCKER_COMPOSE_FILE_PATH"
tee 和 echo 哪个在不同的发行版中更常见啊？

2023-04-14 01:56 UTC, YkeLit commented on compose-upgrade/entrypoint.sh
> +		"tee $INPUT_DOCKER_COMPOSE_FILE_PATH"
两个命令都是 Linux 发行版的基础命令，系统都自带除非人为删除

2023-04-14 02:30 UTC, fahchen commented
没啥问题了，给一个成功运行的 action 的日志

2023-04-14 02:36 UTC, YkeLit commented
> 

https://github.com/Byzanteam/jet-autoflow-example/actions/runs/4695789123/jobs/8325288273
调用这个 actions 的日志

2023-04-14 03:16 UTC, fahchen requested changes

2023-04-14 03:16 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +echo "🚧 Start to upgrade"
这个 日志 使用 GitHub actions 提供的来打吧
参考 https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines

2023-04-14 07:28 UTC, YkeLit commented on compose-upgrade/entrypoint.sh
> +echo "🚧 Start to upgrade"
这感觉不太对，是改 actions 还是改调用的 workflow 哦
![image](https://user-images.githubusercontent.com/48484963/231973737-aed9fa54-04eb-438a-b198-1c8688401a5f.png)

2023-04-14 07:55 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +echo "🚧 Start to upgrade"
改 action，应该没对

2023-04-14 09:20 UTC, YkeLit commented
这样
![image](https://user-images.githubusercontent.com/48484963/232003181-c556bac4-bac1-4f40-b1c5-43c257fe3390.png)

2023-04-14 09:35 UTC, YkeLit commented
https://github.com/Byzanteam/jet-autoflow-example/actions/runs/4698152058/jobs/8330513538

2023-04-14 11:26 UTC, fahchen commented
> 这样
> 
> ![image](https://user-images.githubusercontent.com/48484963/232003181-c556bac4-bac1-4f40-b1c5-43c257fe3390.png)
> 
> 

可以的，success 打出来吧

2023-04-14 11:28 UTC, fahchen commented
大概 log 是 service xx has been upgraded to xx successfully

2023-04-14 14:53 UTC, YkeLit commented
> 大概 log 是 service xx has been upgraded to xx successfully

这样
<img width="897" alt="image" src="https://user-images.githubusercontent.com/48484963/232078834-8f6d70d2-d57a-4128-a8e5-c01c9375d0e3.png">

2023-04-14 16:13 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +echo "::group::🚧 The $INPUT_SERVICE_NAME upgrade starts on the $INPUT_HOST"
```suggestion
echo "::group::🚧 The $INPUT_SERVICE_NAME service is undergoing an upgrade on $INPUT_HOST"
```

2023-04-14 16:13 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +echo "::group::🚀 Successfully upgraded $INPUT_SERVICE_NAME on $INPUT_HOST!"
```suggestion
echo "::group::🚀 The $INPUT_SERVICE_NAME service has been upgraded on $INPUT_HOST successfully!"
```

2023-04-14 17:35 UTC, YkeLit commented on compose-upgrade/entrypoint.sh
> +echo "::group::🚀 Successfully upgraded $INPUT_SERVICE_NAME on $INPUT_HOST!"
https://github.com/Byzanteam/jet-autoflow-example/actions/runs/4702326047/jobs/8339611474

2023-04-15 01:41 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +echo "::group::🚀 Successfully upgraded $INPUT_SERVICE_NAME on $INPUT_HOST!"
![image](https://user-images.githubusercontent.com/855678/232177058-66fdb757-ff19-4050-967b-c088ad0c4a24.png)
有没可能让 44-46L 的这种 echo 不出现在 log 里

2023-04-15 01:55 UTC, YkeLit commented on compose-upgrade/entrypoint.sh
> +echo "::group::🚀 Successfully upgraded $INPUT_SERVICE_NAME on $INPUT_HOST!"
可以就是要把脚本里的空行都去掉，但是脚本就不太好看了

2023-04-15 06:38 UTC, YkeLit commented on compose-upgrade/entrypoint.sh
> +echo "::group::🚀 Successfully upgraded $INPUT_SERVICE_NAME on $INPUT_HOST!"
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/48484963/232191525-c870fdc7-2fca-460a-8978-22274ec838b9.png">

2023-04-15 13:29 UTC, fahchen commented on compose-upgrade/entrypoint.sh
> +echo "::group::🚀 Successfully upgraded $INPUT_SERVICE_NAME on $INPUT_HOST!"
你看看别人的 action 咋写的呢，有没这种问题

2023-04-16 10:29 UTC, YkeLit commented
咋个撤销这次 force push 呀。。。

2023-04-16 10:30 UTC, YkeLit commented on compose-upgrade/entrypoint.sh
> +echo "::group::🚀 Successfully upgraded $INPUT_SERVICE_NAME on $INPUT_HOST!"
没有找到有这样做的 actions

2023-04-17 02:20 UTC, fahchen requested changes

2023-04-17 02:20 UTC, fahchen commented on compose-upgrade/action.yml
> +description: Deploy to the server
这些对齐 compose-upgrade

2023-04-17 02:34 UTC, YkeLit commented
#55

2023-04-17 02:36 UTC, YkeLit commented on compose-upgrade/entrypoint.sh
> +echo "::group::🚀 Successfully upgraded $INPUT_SERVICE_NAME on $INPUT_HOST!"
#55

2023-04-17 04:07 UTC, fahchen approved these changes

2023-04-17 06:02 UTC, merged