chore: 修改 actions 推送 image 到阿里云与 GitHub registry
Byzanteam/jet-actions pull request #54
Opened 2023-04-10 06:09 UTC by YkeLit

* 添加登录阿里云 registry 信息
* 添加推送阿里云 registry tag
* 使用 self hosted 后将缓存保存到本地
> [测试 actions](https://github.com/Byzanteam/jet-autoflow-example/actions/runs/4654150371)

2023-04-10 06:14 UTC, fahchen requested changes

2023-04-10 06:14 UTC, fahchen commented on fe-build-image/README.md
> +    aliyun_namespace: "jet or skylark"
这样设计扩展性不好，这里设计成任意一个 registry 都支持的形式，甚至多个 registries 也行。
另外把 ghr 也当作一个 registry，只是它是默认值，如果有填写的话就以填写的为准

2023-04-10 08:10 UTC, moonRider requested changes

2023-04-10 08:10 UTC, moonRider commented on fe-build-image/action.yml
> +        do
这个感觉不太对呢

2023-04-10 08:15 UTC, moonRider requested changes

2023-04-10 08:15 UTC, moonRider commented on fe-build-image/action.yml
> +          ${{ format('{0}/{1}/${2}:{3}', inputs.registries, inputs.registries_namespace, steps.get-app-info.outputs.name, steps.get-app-info.outputs.version) }}
https://docs.docker.com/build/ci/github-actions/manage-tags-labels/

2023-04-10 08:15 UTC, moonRider commented on fe-build-image/action.yml
> +  registries_key:
这个没用啊，应该就是 registry， username 和 password 吧

2023-04-10 08:28 UTC, YkeLit commented on fe-build-image/action.yml
> +        do
这个就是没对。。。

2023-04-11 03:14 UTC, YkeLit commented on fe-build-image/README.md
> +    aliyun_namespace: "jet or skylark"
现在有以下几个问题：
1. 多个 registries 的作用，现在我们推送两个 registries， 一个国内一个国外，这两个 registries 已经满足我们的使用场景
2. 需要不需要将 registries 设置成变量，如果我们后面切换到其他 registry 这样的话相当于增加工作量，每个 repo 要改一下这个变量；如果是当前 registry 满了，将后面增加 repo 推送到其他 registry 这样设置就没问题。

2023-04-11 05:57 UTC, fahchen commented on fe-build-image/README.md
> +    aliyun_namespace: "jet or skylark"
你考虑的这个问题很好哈。
你在设计工具的时候应当考虑不要把这些东西写死了，如果它是一个更通用的工具将会更适应你第二个问题。另外维护 registry 地址这个的手段可以做到 org 级别去，这样维护一处就好了，不用全局改哈。
在我看来保持现状和支持现在的做法可能开发量和难度没有什么区别，所以倾向于更通用的工具。

2023-04-11 06:00 UTC, fahchen commented on fe-build-image/action.yml
> +          ${{ format('{0}/{1}/${2}:{3}', inputs.registries, inputs.registries_namespace, steps.get-app-info.outputs.name, steps.get-app-info.outputs.version) }}
@YkeLit 参考这个链接的做法

2023-04-12 15:44 UTC, fahchen requested changes

2023-04-12 15:44 UTC, fahchen commented on fe-build-image/action.yml
> +    description: The list of registries URLs
这里声明一下格式

2023-04-12 15:44 UTC, fahchen commented on fe-build-image/action.yml
> +            break
遇到空行就跳过，不用结束循环
```suggestion
            continue
```

2023-04-12 15:44 UTC, fahchen commented on fe-build-image/action.yml
> +            break
```suggestion
            continue
```

2023-04-12 15:44 UTC, fahchen commented on fe-build-image/action.yml
> +            $(echo $line | awk -F',' '{print $1}')
使用一下变量吧，别一行写完了，可读性不高

2023-04-12 15:44 UTC, fahchen commented on fe-build-image/action.yml
> +          ${{ steps.registries.outputs.images}}
这样行不？
```suggestion
        images: ${{ steps.registries.outputs.images }}
```

2023-04-12 15:44 UTC, fahchen commented on fe-build-image/action.yml
> +          ${{ steps.registries.outputs.images}}
空格！
```suggestion
        images: |
          ${{ steps.registries.outputs.images }}
```

2023-04-12 15:44 UTC, fahchen commented on fe-build-image/action.yml
> +          type=sha
这些类型是怎么决定的？

2023-04-12 15:44 UTC, fahchen commented on fe-build-image/action.yml
> +          ${{ inputs.build_args }}
这个为啥在 label 里面？

2023-04-12 15:44 UTC, fahchen commented on fe-build-image/action.yml
> +        build-args: ${{ steps.meta.outputs.labels }}
build-args 和 label 不是一个东西哦

2023-04-12 15:44 UTC, fahchen commented on fe-build-image/action.yml
> +
这个要手动做吗？贴一下链接

2023-04-13 01:38 UTC, YkeLit commented on fe-build-image/action.yml
> +
https://docs.docker.com/build/ci/github-actions/cache/

2023-04-13 01:40 UTC, YkeLit commented on fe-build-image/action.yml
> +          ${{ inputs.build_args }}
确实是我把这个 labels 和 build-args 搞错了

2023-04-13 01:42 UTC, YkeLit commented on fe-build-image/action.yml
> +          ${{ steps.registries.outputs.images}}
可以这样写，但是加 | 是不是更能明确这个地方是有多行输入的值

2023-04-13 01:47 UTC, fahchen commented on fe-build-image/action.yml
> +
local cache 需要做 clean，我们应该用 gha 来做缓存

2023-04-13 01:49 UTC, fahchen commented on fe-build-image/action.yml
> +
你现在代码改成了 local，还没有设置 cache step，所以现在的做法不对

2023-04-13 01:51 UTC, fahchen commented on fe-build-image/action.yml
> +          ${{ steps.registries.outputs.images}}
没必要哈，你看看下面 `Build and push` 那一步设置的 `build-args` 和 `tags` 同样是多行，你就知道你的思考前后不一致了

2023-04-13 02:05 UTC, YkeLit commented on fe-build-image/action.yml
> +        build-args: ${{ steps.meta.outputs.labels }}
这里 build-args 还需要加上 APP_NAME 和 APP_VERSION 吗，这两个变量应该可以从 image 信息很直观看到吧

2023-04-13 02:08 UTC, fahchen commented on fe-build-image/action.yml
> +        build-args: ${{ steps.meta.outputs.labels }}
之前是怎么样的就怎么样，你这个 PR 不要改动这些

2023-04-13 02:57 UTC, YkeLit commented on fe-build-image/action.yml
> +
https://github.com/Byzanteam/jet-autoflow-example/actions/runs/4680335807/jobs/8301661598
这个问题我一直没发解决，所以没有用 gha 做 cache
![image](https://user-images.githubusercontent.com/48484963/231636601-600c3dbc-cd30-4bec-a0f1-b1b6689c2b88.png)

2023-04-13 02:58 UTC, YkeLit commented on fe-build-image/action.yml
> +
设置 cache step，这个是怎么个操作呀

2023-04-13 03:19 UTC, YkeLit commented on fe-build-image/action.yml
> +          type=sha
- schedule 是要去掉的，我们没有每天的定时任务
- ref，这两个 event 
  - 推送分支时，以分支名作为标签
  - pr 合并时，以 pr-num 作为标签
- semver，这三个分别是

Git tag | Pattern | Output
-- | -- | --
v1.2.3 | {{version}} | 1.2.3
v1.2.3 | {{major}}.{{minor}} | 1.2
v1.2.3 | v{{major}} | v1
- sha，就是每次都会有个随机标签来表示当前 image

ref 类型可以用作后面 pr预览或分支预览的image
sha 类型可以做为 image 的历史记录，避免上边标签重复后将这个 image 给覆盖掉

2023-04-13 08:56 UTC, YkeLit commented on fe-build-image/action.yml
> +            break
这个判断我去掉了，使用这个判断的原因本身是应为转换成shell变量的时候会多一个空行，我把 yaml 中 | 改成 |- 就不会有这个问题了

2023-04-13 10:56 UTC, fahchen requested changes

2023-04-13 10:56 UTC, fahchen commented on fe-build-image/action.yml
> +          docker login -u $USERNAME -p $PASSWORD $REGISTRY
贴一下执行成功的链接，这里 -p 是不是有问题，应该是 stdin 的形式输入 password

2023-04-13 10:56 UTC, fahchen commented on fe-build-image/action.yml
> +          type=ref,event=pr
这两个有明确诉求需要吗

2023-04-13 10:56 UTC, fahchen commented on fe-build-image/action.yml
> +    description: "The list of registries. Format like this: registry-site,namespace,username,password"
每一行一个 registry

2023-04-13 10:56 UTC, fahchen commented on fe-build-image/action.yml
> +      shell: bash
这个是不是可以给默认值啊，不用每一步都给

2023-04-13 10:56 UTC, fahchen commented on fe-build-image/action.yml
> +        echo "image_name=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
@moonRider  image name 从 repo 去取应该有没有问题，之前是从 package.json 取的

2023-04-13 10:59 UTC, moonRider commented on fe-build-image/action.yml
> +        echo "image_name=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
一个项目多个部署（比如数字大面，桂溪中和这种）从仓库获取到是一样的

2023-04-13 11:39 UTC, YkeLit commented on fe-build-image/action.yml
> +          type=ref,event=pr
我们有分支预览的需求，这两个一个可以打包当前分支的镜像一个可以打包当前 pr 的镜像。这两个算不算需求

2023-04-13 11:42 UTC, YkeLit commented on fe-build-image/action.yml
> +      shell: bash
这里直接调用 secrets 变量的话要报错，找不到这个变量。不过没有测试过在 org 里设置 secret 能不能调用，需要协助一下添加一个.

2023-04-13 11:47 UTC, YkeLit commented on fe-build-image/action.yml
> +          docker login -u $USERNAME -p $PASSWORD $REGISTRY
这里我还是改成 stdin 输入吧，这样稍微不太安全

2023-04-13 13:00 UTC, fahchen commented on fe-build-image/action.yml
> +      shell: bash
看下这个 https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs
是否可以不用每个 step 都设置 shell 这个参数

2023-04-13 13:03 UTC, fahchen commented on fe-build-image/action.yml
> +          type=ref,event=pr
这个可以，但应该用一个就够了吧

2023-04-13 13:03 UTC, fahchen commented on fe-build-image/action.yml
> +        echo "image_name=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
你说的这个不影响镜像啊？你考虑下 monorepo 有没有问题吧

2023-04-13 13:05 UTC, fahchen commented on fe-build-image/action.yml
> +
看提示是暂时不能用

> https://github.com/Byzanteam/jet-autoflow-example/actions/runs/4680335807/jobs/8301661598
> 这个问题我一直没发解决，所以没有用 gha 做 cache
> ![image](https://user-images.githubusercontent.com/48484963/231636601-600c3dbc-cd30-4bec-a0f1-b1b6689c2b88.png)

2023-04-13 13:05 UTC, fahchen requested changes

2023-04-13 13:05 UTC, fahchen commented on fe-build-image/action.yml
> +
> 设置 cache step，这个是怎么个操作呀

你把例子从头看一遍，然后对比下你缺失什么步骤
docker/metadata-action

2023-04-13 15:41 UTC, fahchen requested changes

2023-04-13 15:41 UTC, fahchen commented on fe-build-image/action.yml
> +    description: "The list of registries. Line one value : registry-site,namespace,username,password"
```suggestion
    description: "This parameter is a list of registries separated by a newline character. Each registry should be formatted as follows: ${hostname},${namespace},${username},${password}."
```

2023-04-13 15:41 UTC, fahchen commented on fe-build-image/action.yml
> +          type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
为什么这两种情况不开启啊？

2023-04-13 15:41 UTC, fahchen commented on fe-build-image/action.yml
> +          APP_VSN=${{ steps.meta.outputs.version }}
如果是 branch 或 pr 这种情况，meta.outputs.version 的值是什么？

2023-04-13 15:41 UTC, fahchen commented on fe-build-image/action.yml
> +
用 gha 缓存

2023-04-13 15:51 UTC, YkeLit commented on fe-build-image/action.yml
> +          APP_VSN=${{ steps.meta.outputs.version }}
pr 这种情况是 pr-num

2023-04-13 15:57 UTC, YkeLit commented on fe-build-image/action.yml
> +          type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
如果 tag 是 v0.0.1 这样的话
{{major}}.{{minor}} 是 0.0
{{major}} 是 0
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/48484963/231816892-59db3693-e832-4553-9a84-6d8ceabf7419.png">

2023-04-13 16:53 UTC, YkeLit commented on fe-build-image/action.yml
> +      shell: bash
测试了，不支持

2023-04-13 17:00 UTC, YkeLit commented
<img width="956" alt="image" src="https://user-images.githubusercontent.com/48484963/231831342-cca7f548-81bc-40fb-98e5-9f6a134798ac.png">
使用 `echo "$PASSWORD" | docker login -u $USERNAME --password-stdin $REGISTRY` 命令报错信息
### 先保存错误

2023-04-14 08:06 UTC, YkeLit commented
@fahchen 我现在有两个方案来分别 使用 self hosted 和 github hosted
第一个是设置 cache_dir 变量
```
inputs:
  cache_dir: /tmp/.buildx-cache

runs:
  steps:
    - if: ${{ inputs.cache_dir != '' }}
      id: cache
      run: |
        echo "cache-from=\"type=local,src=${{ inputs.cache_dir }}-${{ steps.image.outputs.image_name }}\"" >> $GITHUB_OUTPUT
        echo "cache-to=\"type=local,dest=${{ inputs.cache_dir }}-new-${{ steps.image.outputs.image_name }}\"" >> $GITHUB_OUTPUT

    - if: ${{ inputs.cache_dir = '' }}
      id: cache
      run: |
        echo "cache-from=\"type=gha\"" >> $GITHUB_OUTPUT
        echo "cache-to=\"type=gha\"" >> $GITHUB_OUTPUT

    - uses: docker/build-push-action@v3
       with:
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}, mode=max

    - if: ${{ inputs.cache_dir != '' }}
      name: Move cache
      shell: bash
      run: |
        rm -rf ${{ steps.cache.outputs.cache-from }}
        mv ${{ steps.cache.outputs.cache-to }} ${{ steps.cache.outputs.cache-from }}
```
第二个是通过 cache_type
```
inputs:
  cache_type: local

runs:
  steps:
    - if: ${{ inputs.cache_type == 'local' }}
       uses: docker/build-push-action@v3
       with:
          cache-from: type=${{ inputs.cache_type }},src=/tmp/.buildx-cache-${{ steps.image.outputs.image_name }}
          cache-to: type=${{ inputs.cache_type }},src=/tmp/.buildx-cache-new-${{ steps.image.outputs.image_name }}, mode=max

    - if: ${{ inputs.cache_type == 'gha' }}
       uses: docker/build-push-action@v3
       with:
          cache-from: type=${{ inputs.cache_type }}
          cache-to: type=${{ inputs.cache_type }},mode=max

    - if: ${{ inputs.cache_type == 'local' }}
      name: Move cache
      shell: bash
      run: |
        rm -rf /tmp/.buildx-cache-${{ steps.image.outputs.image_name }}
        mv /tmp/.buildx-cache-new-${{ steps.image.outputs.image_name }} /tmp/.buildx-cache-${{ steps.image.outputs.image_name }}
```

2023-04-14 08:09 UTC, fahchen commented
> @fahchen 我现在有两个方案来分别 使用 self hosted 和 github hosted 第一个是设置 cache_dir 变量
> 
> ```
> inputs:
>   cache_dir: /tmp/.buildx-cache
> 
> runs:
>   steps:
>     - if: ${{ inputs.cache_dir != '' }}
>       id: cache
>       run: |
>         echo "cache-from=\"type=local,src=${{ inputs.cache_dir }}-${{ steps.image.outputs.image_name }}\"" >> $GITHUB_OUTPUT
>         echo "cache-to=\"type=local,dest=${{ inputs.cache_dir }}-new-${{ steps.image.outputs.image_name }}\"" >> $GITHUB_OUTPUT
> 
>     - if: ${{ inputs.cache_dir = '' }}
>       id: cache
>       run: |
>         echo "cache-from=\"type=gha\"" >> $GITHUB_OUTPUT
>         echo "cache-to=\"type=gha\"" >> $GITHUB_OUTPUT
> 
>     - uses: docker/build-push-action@v3
>        with:
>           cache-from: ${{ steps.cache.outputs.cache-from }}
>           cache-to: ${{ steps.cache.outputs.cache-to }}, mode=max
> 
>     - if: ${{ inputs.cache_dir != '' }}
>       name: Move cache
>       shell: bash
>       run: |
>         rm -rf ${{ steps.cache.outputs.cache-from }}
>         mv ${{ steps.cache.outputs.cache-to }} ${{ steps.cache.outputs.cache-from }}
> ```
> 
> 第二个是通过 cache_type
> 
> ```
> inputs:
>   cache_type: local
> 
> runs:
>   steps:
>     - if: ${{ inputs.cache_type == 'local' }}
>        uses: docker/build-push-action@v3
>        with:
>           cache-from: type=${{ inputs.cache_type }},src=/tmp/.buildx-cache-${{ steps.image.outputs.image_name }}
>           cache-to: type=${{ inputs.cache_type }},src=/tmp/.buildx-cache-new-${{ steps.image.outputs.image_name }}, mode=max
> 
>     - if: ${{ inputs.cache_type == 'gha' }}
>        uses: docker/build-push-action@v3
>        with:
>           cache-from: type=${{ inputs.cache_type }}
>           cache-to: type=${{ inputs.cache_type }},mode=max
> 
>     - if: ${{ inputs.cache_type == 'local' }}
>       name: Move cache
>       shell: bash
>       run: |
>         rm -rf /tmp/.buildx-cache-${{ steps.image.outputs.image_name }}
>         mv /tmp/.buildx-cache-new-${{ steps.image.outputs.image_name }} /tmp/.buildx-cache-${{ steps.image.outputs.image_name }}
> ```

cache_dir 允许指定吗？

2023-04-14 08:40 UTC, YkeLit commented
> > @fahchen 我现在有两个方案来分别 使用 self hosted 和 github hosted 第一个是设置 cache_dir 变量
> > ```
> > inputs:
> >   cache_dir: /tmp/.buildx-cache
> > 
> > runs:
> >   steps:
> >     - if: ${{ inputs.cache_dir != '' }}
> >       id: cache
> >       run: |
> >         echo "cache-from=\"type=local,src=${{ inputs.cache_dir }}-${{ steps.image.outputs.image_name }}\"" >> $GITHUB_OUTPUT
> >         echo "cache-to=\"type=local,dest=${{ inputs.cache_dir }}-new-${{ steps.image.outputs.image_name }}\"" >> $GITHUB_OUTPUT
> > 
> >     - if: ${{ inputs.cache_dir = '' }}
> >       id: cache
> >       run: |
> >         echo "cache-from=\"type=gha\"" >> $GITHUB_OUTPUT
> >         echo "cache-to=\"type=gha\"" >> $GITHUB_OUTPUT
> > 
> >     - uses: docker/build-push-action@v3
> >        with:
> >           cache-from: ${{ steps.cache.outputs.cache-from }}
> >           cache-to: ${{ steps.cache.outputs.cache-to }}, mode=max
> > 
> >     - if: ${{ inputs.cache_dir != '' }}
> >       name: Move cache
> >       shell: bash
> >       run: |
> >         rm -rf ${{ steps.cache.outputs.cache-from }}
> >         mv ${{ steps.cache.outputs.cache-to }} ${{ steps.cache.outputs.cache-from }}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 第二个是通过 cache_type
> > ```
> > inputs:
> >   cache_type: local
> > 
> > runs:
> >   steps:
> >     - if: ${{ inputs.cache_type == 'local' }}
> >        uses: docker/build-push-action@v3
> >        with:
> >           cache-from: type=${{ inputs.cache_type }},src=/tmp/.buildx-cache-${{ steps.image.outputs.image_name }}
> >           cache-to: type=${{ inputs.cache_type }},src=/tmp/.buildx-cache-new-${{ steps.image.outputs.image_name }}, mode=max
> > 
> >     - if: ${{ inputs.cache_type == 'gha' }}
> >        uses: docker/build-push-action@v3
> >        with:
> >           cache-from: type=${{ inputs.cache_type }}
> >           cache-to: type=${{ inputs.cache_type }},mode=max
> > 
> >     - if: ${{ inputs.cache_type == 'local' }}
> >       name: Move cache
> >       shell: bash
> >       run: |
> >         rm -rf /tmp/.buildx-cache-${{ steps.image.outputs.image_name }}
> >         mv /tmp/.buildx-cache-new-${{ steps.image.outputs.image_name }} /tmp/.buildx-cache-${{ steps.image.outputs.image_name }}
> > ```
> 
> cache_dir 允许指定吗？

cache_dir 允许指定，但是 cache 这个 ID 产生冲突了，我准备使用第二种方式

2023-04-14 09:10 UTC, YkeLit commented
[GitHub hosted build 测试结果 cache_type: gha](https://github.com/Byzanteam/jet-autoflow-example/actions/runs/4698152056/workflow)
[Self hosted build 测试结果 cache_type: local](https://github.com/Byzanteam/jet-autoflow-example/actions/runs/4698067132)

2023-04-14 11:24 UTC, fahchen requested changes

2023-04-14 11:24 UTC, fahchen commented on fe-build-image/action.yml
> +    required: true
这个得有默认值，默认值填 GitHub ，不然这个 pr 一合并那些 repo 都跑不起来

2023-04-14 15:01 UTC, YkeLit commented on fe-build-image/action.yml
> +    required: true
设置默认值 `ghcr.io,byzanteam,${{ github.repository_owner }},${{ secrets.GITHUB_TOKEN }}`，这个 secrets 需要在哪里设置一下
<img width="919" alt="image" src="https://user-images.githubusercontent.com/48484963/232080617-9a9f8039-2faf-4f03-8ca3-60c088ab809b.png">

2023-04-14 16:14 UTC, fahchen commented on fe-build-image/action.yml
> +    required: true
secret 这个直接取 GitHub context 下的就行

2023-04-14 17:26 UTC, YkeLit commented on fe-build-image/action.yml
> +    required: true
Ok 了
https://github.com/Byzanteam/jet-autoflow-example/actions/runs/4702326055/jobs/8339444357

2023-04-15 00:53 UTC, fahchen requested changes
package file 那个参数还有用没？

2023-04-15 00:53 UTC, fahchen commented on fe-build-image/action.yml
> +  run:
这个下面没值吗

2023-04-15 00:53 UTC, fahchen commented on fe-build-image/action.yml
> +    required: true
要不还是保留 github_token 那个 input，改成 optional 的

2023-04-15 00:53 UTC, fahchen commented on fe-build-image/README.md
> +  ghcr.io,byzanteam,${{ github.repository_owner }},${{ secrets.GITHUB_TOKEN }}
修改例子 token

2023-04-15 00:53 UTC, fahchen commented on fe-build-image/action.yml
> +    description: When using self hosted to builds the image, should set the cache storage directory
说明目前只支持 gha 和 local

2023-04-15 06:25 UTC, YkeLit commented on fe-build-image/action.yml
> +    description: When using self hosted to builds the image, should set the cache storage directory
这个写 README 里就可以了吧

2023-04-17 06:31 UTC, fahchen requested changes

2023-04-17 06:31 UTC, fahchen commented on branch-preview/package-lock.json
这个不属于当前的改动不要引入进来啊

2023-04-17 06:31 UTC, fahchen commented on fe-build-image/action.yml
> +    default: ghcr.io,byzanteam,${{ github.repository_owner }},${{ github.token }}
composite action 可以取到 github.token 吗？之前是不能取到的，所以通过 inputs 传入的

2023-04-17 06:31 UTC, fahchen commented on fe-build-image/action.yml
> +        cache-to: type=${{ inputs.cache_type }},mode=max
这里不用再取变量了，if 已经判断了这里一定是 gha
```suggestion
        cache-from: type=gha
        cache-to: type=gha,mode=max
```

2023-04-17 06:31 UTC, fahchen commented on fe-build-image/action.yml
> +        done
这个做成 `Login to the custom registries` 那一步的 post 操作试试

2023-04-17 08:20 UTC, YkeLit commented on fe-build-image/action.yml
> +    default: ghcr.io,byzanteam,${{ github.repository_owner }},${{ github.token }}
可以去到，这个是 GitHub 的 上下文，之前是 secret 所以会报错

2023-04-17 08:48 UTC, YkeLit commented on fe-build-image/action.yml
> +        done
这个post 操作仅支持 JavaScript 方式
[runs.post](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runspost)

2023-04-17 09:20 UTC, fahchen approved these changes, later dismissed

2023-04-17 09:31 UTC, moonRider commented on fe-build-image/action.yml
> +        echo "image_name=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
monorepo 没有影响。项目型的monorepo，只有项目对应的包会生成镜像。工具或库类型的包没有镜像。不冲突

2023-04-17 09:35 UTC, moonRider approved these changes, later dismissed

2023-04-17 10:19 UTC, fahchen commented on fe-build-image/action.yml
> +        echo "image_name=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
额，我问的是项目的名字的取法有没问题，不是怎么打镜像

2023-04-17 10:22 UTC, moonRider commented on fe-build-image/action.yml
> +        echo "image_name=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
> 额，我问的是项目的名字的取法有没问题，不是怎么打镜像

项目名字没问题

2023-04-18 06:20 UTC, YkeLit commented
@moonRider @c01dcat 麻烦 review 下

2023-04-18 06:29 UTC, moonRider requested changes

2023-04-18 06:29 UTC, moonRider commented on fe-build-image/action.yml
> +        echo "image_name=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
image_name 有空格是允许的吗？`basename jet-hive` 这样的不太对吧

2023-04-18 06:45 UTC, YkeLit commented on fe-build-image/action.yml
> +        echo "image_name=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
那还是只能用 package.json 文件

2023-04-18 06:57 UTC, fahchen commented on fe-build-image/action.yml
> +        echo "image_name=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
> image_name 有空格是允许的吗？`basename jet-hive` 这样的不太对吧

😅，basename 是一个命令

2023-04-18 06:58 UTC, fahchen commented on fe-build-image/action.yml
> +        echo "image_name=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
@moonRider 你们有的 mono repo 不是用的 repo 的名字来作为发布的镜像的名字吧？你查一遍哦，不然这个 PR 合并了，有些 repo 工作不起来的

2023-04-18 07:35 UTC, moonRider commented on fe-build-image/action.yml
> +        echo "image_name=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
> @moonRider 你们有的 mono repo 不是用的 repo 的名字来作为发布的镜像的名字吧？你查一遍哦，不然这个 PR 合并了，有些 repo 工作不起来的

目前就只有 jet-hive 和 jet-hive-admin 用了 monorepo，且只有 jet-hive-admin 需要生成镜像。 jet-hive-admin 之前的名字改用项目仓库名字的话也是一样的。非 jet 项目目前没看到有用 monorepo 的

2023-04-18 10:57 UTC, fahchen commented on fe-build-image/action.yml
> +        echo "image_name=`basename ${{ github.repository }}`" >> $GITHUB_OUTPUT
那我没问题了

2023-04-18 17:24 UTC, YkeLit commented on fe-build-image/README.md
>      docker_file: ./deploy/Dockerfile
这里变量名错误

2023-04-18 17:25 UTC, YkeLit commented on fe-build-image/README.md
>      docker_file: ./deploy/Dockerfile
变量名 dockerfile

2023-04-18 17:26 UTC, YkeLit commented on fe-build-image/README.md
>      docker_file: ./deploy/Dockerfile
变量名 dockerfile

2023-04-19 02:24 UTC, fahchen commented on fe-build-image/README.md
> +    package_file: package.json
你咋又改回去了， @moonRider 说现在的获取方式是可以的嘛？

2023-04-19 06:55 UTC, YkeLit commented on fe-build-image/README.md
> +    package_file: package.json
理解错了抱歉

2023-04-19 07:06 UTC, moonRider approved these changes, later dismissed

2023-04-19 07:49 UTC, fahchen approved these changes, later dismissed

2023-04-19 07:50 UTC, fahchen commented
> * 添加登录阿里云 registry 信息
> * 添加推送阿里云 registry tag
> * 使用 self hosted 后将缓存保存到本地
> 
> > [测试 actions](https://github.com/Byzanteam/jet-autoflow-example/actions/runs/4654150371)

更新一下测试的 action，重新跑一下哈

2023-04-19 10:25 UTC, YkeLit commented
> > * 添加登录阿里云 registry 信息
> > * 添加推送阿里云 registry tag
> > * 使用 self hosted 后将缓存保存到本地
> > 
> > > [测试 actions](https://github.com/Byzanteam/jet-autoflow-example/actions/runs/4654150371)
> 
> 更新一下测试的 action，重新跑一下哈

[local hosted](https://github.com/Byzanteam/jet-autoflow-example/actions/runs/4742155710/jobs/8420105325) 
[github hosted](https://github.com/Byzanteam/jet-autoflow-example/actions/runs/4742014336/jobs/8419807384)
[测试 release 发布](https://github.com/Byzanteam/jet-autoflow-example/actions/runs/4742214389)

2023-04-19 10:38 UTC, fahchen approved these changes

2023-04-19 11:15 UTC, c01dcat submitted a review, later dismissed

2023-04-20 03:30 UTC, fahchen submitted a review, later dismissed

2023-04-20 05:42 UTC, fahchen approved these changes

2023-04-20 05:42 UTC, merged