feat: deploy frontend application GitHub action
Byzanteam/jet-actions pull request #56
Opened 2023-05-17 10:06 UTC by YkeLit

- 通过编写 values 文件，使用 helm chart 进行部署

2023-05-18 02:41 UTC, fahchen requested changes

2023-05-18 02:41 UTC, fahchen commented on front-deploy/action.yml
> +    required: true
这个我们需要在每个项目里面再填一次吗

2023-05-18 02:41 UTC, fahchen commented on front-deploy/action.yml
> +    required: true
这里只要 tag 吗，不需要填 image （如 `ghcr.io/byzanteam/jet-hive-admin:1.0.0`） 吗？

2023-05-18 02:41 UTC, fahchen commented on front-deploy/action.yml
> +ame: front pr preview deploy
```suggestion
name: front pr preview deploy
```

2023-05-18 02:41 UTC, fahchen commented on front-deploy/action.yml
> +description: "前端提交pull request 自动部署并反向代理"
相关的名字，文件及注释都改成 deploy-frontend- application

2023-05-18 02:41 UTC, fahchen commented on front-deploy/README.md
> +```
这个不需要了，这个 action 用于部署前端应用

2023-05-18 04:50 UTC, YkeLit commented on front-deploy/action.yml
> +    required: true
这个只需要在 org 里设置就可以了，不用每个都填

2023-05-18 04:50 UTC, YkeLit commented on front-deploy/action.yml
> +    required: true
只用设置 tag 因为 values 文件里有 `ghcr.io/byzanteam/jet-hive-admin` 这一段

2023-05-18 05:10 UTC, YkeLit commented
测试运行的 actions：
https://github.com/Byzanteam/jet-autoflow-example/actions/runs/5010198631

部署后的网页：
http://example.official.jet.work/

2023-05-18 05:20 UTC, fahchen commented on front-deploy/action.yml
> +    required: true
我们不需要登陆了吧，在 k8s 里面登陆一次就行了吧

2023-05-18 05:22 UTC, fahchen requested changes
之前没 resolve 的 comments 修改完

2023-05-18 05:22 UTC, fahchen commented on front-deploy/action.yml
> +    required: true
这两个给下默认值

2023-05-18 06:00 UTC, fahchen commented on front-deploy/README.md
这里给一下描述这个 action 是做什么的
参考 https://github.com/Byzanteam/jet-actions/blob/main/branch-preview/README.md

2023-05-18 06:18 UTC, YkeLit commented on front-deploy/action.yml
> +    required: true
k8s 通过 secret 去获取信息然后拉取私有镜像仓库的镜像，但是不会保存登录状态。每个helm chat 的这个 secret 名称不一样所以每个 repo 都要去生成一个 secret 登录信息。

2023-05-18 06:28 UTC, YkeLit commented on front-deploy/action.yml
> +    required: true
这个 host 使用 官网那个服务器作为默认值吗

2023-05-18 07:08 UTC, fahchen commented on front-deploy/action.yml
> +    required: true
你设置了 password，那 username 呢？你让认证需要的信息发生在服务器上面吧

2023-05-18 07:08 UTC, fahchen commented on front-deploy/action.yml
> +    required: true
部署应用的那台服务器

2023-05-18 07:11 UTC, fahchen requested changes

2023-05-18 07:11 UTC, fahchen commented on front-deploy/README.md
民宅改成 deploy-frontend-application

2023-05-18 07:11 UTC, fahchen commented on front-deploy/README.md
> +| Key                 | Request | Default                    |
加一列用来写例子

2023-05-18 07:11 UTC, fahchen commented on front-deploy/action.yml
> +    default: 120.27.135.51
这里用域名吧，不用 ip
另外我们应用部署的域名不要用二级域名，用三级域名 `*.apps.jet.work`

2023-05-18 10:04 UTC, fahchen requested changes
问题没改完

2023-05-19 06:24 UTC, YkeLit commented on front-deploy/action.yml
> +    required: true
这个我可以直接用 repo 的名字吗，设置这个是不是有点多余了

2023-05-19 06:24 UTC, YkeLit commented on front-deploy/action.yml
> +    required: true
username 在 values 文件里， 把密码放出来免得被盗用

2023-05-19 06:24 UTC, YkeLit commented on front-deploy/action.yml
> +    required: true
这个域名是对应的部署应用那台服务器，这是新开的服务器

2023-05-19 06:24 UTC, YkeLit commented on front-deploy/action.yml
> +    default: 120.27.135.51
好了

2023-05-19 09:31 UTC, YkeLit commented
调整完了
[不添加 release_name 运行结果](https://github.com/Byzanteam/jet-autoflow-example/actions/runs/5022793713)
[添加 release_name 运行结果](https://github.com/Byzanteam/jet-autoflow-example/actions/runs/5022610441)

2023-05-22 05:57 UTC, fahchen commented
例子也贴一下哇

2023-05-22 07:38 UTC, YkeLit commented
> 例子也贴一下哇

我把例子写在这个 repo 中了
https://github.com/Byzanteam/jet-autoflow-example/pull/4

2023-05-22 07:57 UTC, fahchen requested changes
也把它作为整个 action 的输出哈，这样后面的 action 可以使用这个 action 的 output

2023-05-23 02:01 UTC, fahchen requested changes

2023-05-23 02:01 UTC, fahchen commented on deploy-frontend-application/action.yml
> +description: "前端应用部署 actions, 通过 helm chart 在 kubernetes 集群中部署应用"
```suggestion
description: "Deploy a frontend application in the k8s cluster via helm."
```

2023-05-23 02:01 UTC, fahchen commented on deploy-frontend-application/action.yml
> +    value: ${{ steps.domain_name.outputs.domain_name }}
```suggestion
  app_url:
    description: "The public URL for a frontend application deployed on a Kubernetes cluster."
    value: ${{ steps.domain_name.outputs.domain_name }}
```

2023-05-23 02:01 UTC, fahchen commented on deploy-frontend-application/action.yml
> +    - name: Deploy Frontend Application
注意大小写
```suggestion
    - name: Deploy the frontend application
```

2023-05-23 02:01 UTC, fahchen commented on deploy-frontend-application/action.yml
> +
按 output 那里改一下

2023-05-23 02:35 UTC, fahchen requested changes

2023-05-23 02:35 UTC, fahchen commented on deploy-frontend-application/README.md
> +| Key                 | Request | Default                    | Example                                                 |
```suggestion
| Key                 | Required | Default                    | Example                                                 |
```

2023-05-23 02:35 UTC, fahchen commented on deploy-frontend-application/README.md
> +| values_file         | false   | ./deploy/values.local.yaml | values_file: ./deploy/values.local.yaml                 |
在例子里面不要那个 key 
```suggestion
| values_file         | false   | ./deploy/values.local.yaml | ./deploy/values.local.yaml                 |
```

2023-05-23 02:35 UTC, fahchen commented on deploy-frontend-application/README.md
> +    namespace: dev
这个用最少的参数，大部分用默认值就够了
```suggestion
    values_file: ./deploy/values.local.yaml
    image_tag: 1.0.0
    private_key: ${{ secrets.SSH_KEY }}
```

2023-05-23 02:35 UTC, fahchen commented on deploy-frontend-application/README.md
> +* The test namespace corresponds to the test environment
namespace 我们支持几个啊？

2023-05-23 06:26 UTC, YkeLit commented on deploy-frontend-application/README.md
> +* The test namespace corresponds to the test environment
namespace 没有做限制，现在目前用三个应该是可以的吧，default， dev 和 test

2023-05-24 02:06 UTC, fahchen commented on deploy-frontend-application/README.md
> +* The test namespace corresponds to the test environment
要不校验一下，我们只允许几个 namespace
你列一下每个 namespace 及用途

2023-05-25 01:51 UTC, fahchen requested changes

2023-05-25 01:51 UTC, fahchen commented on deploy-frontend-application/README.md
> +| release_name        | false   | "This repo name"           | frontend-app                                            |
名字应该不允许中间有空格的
```suggestion
| release_name        | false   | my-frontend-app           | frontend-app                                            |
```

2023-05-25 01:51 UTC, fahchen commented on deploy-frontend-application/README.md
> +| image_tag           | true    | ""                         | 1.0.0                                                   |
没有默认值
```suggestion
| image_tag           | true    |                            | 1.0.0                                                   |
```

2023-05-25 01:51 UTC, fahchen commented on deploy-frontend-application/README.md
> +| private_key         | true    | ""                         | ${{ secrets.SSH_KEY }}                                  |
```suggestion
| private_key         | true    |                            | ${{ secrets.SSH_KEY }}                                  |
```

2023-05-25 14:10 UTC, YkeLit commented on deploy-frontend-application/README.md
> +* The test namespace corresponds to the test environment
这个用户只授权了三个 namespace

2023-05-26 00:46 UTC, fahchen requested changes

2023-05-26 00:46 UTC, fahchen commented on deploy-frontend-application/action.yml
> +      id: domain_name
id 改一下，output 的 name 也改一下

2023-05-26 00:46 UTC, fahchen commented on deploy-frontend-application/action.yml
> +    default: default
namespace 允许的值列在这里一下
我们别允许 default 了，目前我们就两个环境 production 和 test。
action 里面校验一下，如果不是这两个 namespace 就报错

2023-05-26 02:01 UTC, YkeLit commented on deploy-frontend-application/action.yml
> +    default: default
这个校验在action里做还直接让主机返回错误呢，因为这两个都是可以的

2023-05-26 02:30 UTC, YkeLit commented on deploy-frontend-application/action.yml
> +    default: default
还有一个情况，项目上如果是skylark 和 jet 公用一个集群的时候，他们其实不应该在一个 production 的 namespace，在 action 里写死了感觉不太好，用 cluster 的权限去约束还好些

2023-05-26 04:21 UTC, fahchen commented on deploy-frontend-application/action.yml
> +    - name: Get repo name
```suggestion
    - name: Set RELEASE_NAME
```

2023-05-26 04:21 UTC, fahchen commented on deploy-frontend-application/action.yml
> +            app-template/application-chart-template"
wrapper
function helm(**args) {
  ssh_connect = ""
  match args[0] {
    "helm" -> {
      ssh -i private.key -o "StrictHostKeyChecking=no" ${{ inputs.user }}@${{ inputs.host }} -p ${{ inputs.port }} \
          "helm upgrade ${args[1]}"

    }
  }
}

helm repo add --force-update app-template https://Byzanteam.github.io/helm-charts

2023-05-26 04:21 UTC, fahchen commented on deploy-frontend-application/action.yml
> +            app-template/application-chart-template"
helm upgrade --install ${{ env.RELEASE_NAME }} \
            -f <<BEGIN \
            --set image.tag=${{ inputs.image_tag }} \
            --namespace ${{ inputs.namespace }} --create-namespace \
            app-template/application-chart-template
template content
<<BEGIN

2023-05-26 09:03 UTC, fahchen requested changes

2023-05-26 09:03 UTC, fahchen commented on deploy-frontend-application/action.yml
> +        END
这两个 step 的代码咋感觉差不多呢？除了 if 判断

2023-05-26 09:03 UTC, fahchen commented on deploy-frontend-application/action.yml
> +      id: public_url
```suggestion
      id: get-public-url
```

2023-05-26 09:03 UTC, fahchen commented on deploy-frontend-application/README.md
> +  * The `test` namespace corresponds to the test environment
这两个 namespace 什么情况下选什么，这个说明清楚一下

2023-05-26 09:27 UTC, YkeLit commented on deploy-frontend-application/action.yml
> +        END
是一样的，我没有找到 if 判断两个值的示例，所以是判断了两次

2023-05-26 09:56 UTC, fahchen commented on deploy-frontend-application/action.yml
> +        END
为啥要分成两个 step？

2023-05-26 10:04 UTC, fahchen requested changes

2023-05-26 10:04 UTC, fahchen commented on deploy-frontend-application/action.yml
> +          production)
单独放一个 step 去校验就好了

2023-05-26 10:05 UTC, fahchen commented on deploy-frontend-application/README.md
> +| release_name        | false   | "This repo name"           | frontend-app                                            |
```suggestion
| release_name        | false   | `$(basename ${{ github.repository }})`           | frontend-app                                            |
```

2023-05-26 10:33 UTC, YkeLit commented on deploy-frontend-application/action.yml
> +        echo "EOF" >> $GITHUB_OUTPUT
这个 outputs 只找到 `helm get values RELEASE_NAME [flags]` 也是输出所有的这个 values 文件的值，需要做文本处理，并且还要多一次 ssh 连接。这里暂时就没有改动它。

2023-05-26 12:19 UTC, fahchen commented on deploy-frontend-application/action.yml
> +          "helm repo add --force-update app-template https://Byzanteam.github.io/helm-charts"
这一步是不是没必要呀？

2023-05-26 12:39 UTC, YkeLit commented on deploy-frontend-application/action.yml
> +          "helm repo add --force-update app-template https://Byzanteam.github.io/helm-charts"
有必要吧，这个可以更新 helm chart repo, 新的环境下也可以保证部署成功。

2023-05-27 00:29 UTC, fahchen commented on deploy-frontend-application/action.yml
> +          "helm repo add --force-update app-template https://Byzanteam.github.io/helm-charts"
helm chart 的更新不属于 deploy 要负责的吧？

2023-05-27 02:55 UTC, YkeLit commented on deploy-frontend-application/action.yml
> +          "helm repo add --force-update app-template https://Byzanteam.github.io/helm-charts"
helm chart的更新在 deploy 这里不冲突吧。比如后面我们新加 chart 到仓库里，然后部署新的应用的时候。

2023-05-27 03:08 UTC, fahchen commented on deploy-frontend-application/action.yml
> +          "helm repo add --force-update app-template https://Byzanteam.github.io/helm-charts"
保证这个 action 职责单一

2023-05-27 05:31 UTC, YkeLit commented on deploy-frontend-application/action.yml
> +          "helm repo add --force-update app-template https://Byzanteam.github.io/helm-charts"
deploy 是不是应该包含一下步骤：
  - 设置部署环境
    - helm chart repo 添加与更新是否属于这一步骤
  - 安装应用
  - 测试应用

2023-05-27 05:32 UTC, YkeLit commented on deploy-frontend-application/action.yml
> +          "helm repo add --force-update app-template https://Byzanteam.github.io/helm-charts"
如果值实现安装应用这一步的话，那我就把这删掉

2023-05-27 06:17 UTC, fahchen commented on deploy-frontend-application/action.yml
> +          "helm repo add --force-update app-template https://Byzanteam.github.io/helm-charts"
helm chart repo 添加与更新不属于，这个应当是提前或者单独做

2023-05-27 10:48 UTC, YkeLit commented on deploy-frontend-application/action.yml
> +          "helm repo add --force-update app-template https://Byzanteam.github.io/helm-charts"
改了

2023-05-27 13:08 UTC, fahchen commented
贴一个成功运行的例子

2023-05-27 15:31 UTC, YkeLit commented
> 贴一个成功运行的例子

https://github.com/Byzanteam/jet-autoflow-example/actions/runs/5098404217/jobs/9165522072

2023-05-28 01:22 UTC, fahchen commented
> > 贴一个成功运行的例子
> 
> 
> 
> https://github.com/Byzanteam/jet-autoflow-example/actions/runs/5098404217/jobs/9165522072

把 output 取出来在下一步 echo 出来看看

2023-05-28 02:54 UTC, YkeLit commented
> > > 贴一个成功运行的例子
> > 
> > 
> > 
> > https://github.com/Byzanteam/jet-autoflow-example/actions/runs/5098404217/jobs/9165522072
> 
> 把 output 取出来在下一步 echo 出来看看

最后一步就是去的outputs

2023-05-28 03:39 UTC, fahchen approved these changes

2023-05-28 03:40 UTC, fahchen commented
这个 PR 你回头总结一下问题发我哈

2023-05-28 05:11 UTC, YkeLit commented
> 这个 PR 你回头总结一下问题发我哈

好要得

2023-05-28 05:11 UTC, merged