chore: 添加可选参数 custom_image_name
Byzanteam/jet-actions pull request #57
Opened 2023-06-13 12:43 UTC by YkeLit

可以自定义 image name

2023-06-14 16:47 UTC, fahchen requested changes

2023-06-14 16:47 UTC, fahchen commented on fe-build-image/action.yml
> +  custom_image_name:
```suggestion
  image_name:
```

2023-06-14 16:47 UTC, fahchen commented on fe-build-image/action.yml
> +    description: Custom image name
```suggestion
    description: Set an image name, or derive it from the repo name by default
```

2023-06-18 11:49 UTC, fahchen commented on fe-build-image/action.yml
> +        echo "image_name=$([-n "${{ inputs.image_name }}" ] && echo "${{ inputs.image_name }}" || echo "$REPO_NAME")" >> $GITHUB_OUTPUT
REPO_NAME 的值是怎么样的啊，贴下链接呢

2023-06-18 11:50 UTC, fahchen commented on fe-build-image/README.md
> +    image_name: example_repo
```suggestion
    image_name: my_image
```

2023-06-19 02:40 UTC, YkeLit commented on fe-build-image/action.yml
> +        echo "image_name=$([-n "${{ inputs.image_name }}" ] && echo "${{ inputs.image_name }}" || echo "$REPO_NAME")" >> $GITHUB_OUTPUT
例如这个 repo `Byzanteam/jet-actions`, REPO_NAME 的值为 `jet-actions`

2023-06-19 05:48 UTC, fahchen approved these changes

2023-06-28 08:28 UTC, merged