refactor: Rename deploy-frontend-application
Byzanteam/jet-actions pull request #67
Opened 2023-08-24 08:38 UTC by YkeLit

Rename deploy-frontend-application to deploy-application-charts

2023-08-24 09:33 UTC, fahchen requested changes
1. 顺便到 README 中加一下
2. 文档对应的地方也要改

2023-08-24 11:26 UTC, fahchen requested changes
其它 repo 用到的地方都改一下，把改到了的地方贴一下 list

2023-08-24 12:33 UTC, YkeLit commented
> 
就这一个目前
https://github.com/Byzanteam/jet-work-official-website

2023-08-25 01:46 UTC, fahchen approved these changes

2023-08-25 01:48 UTC, merged