feat: registry login
Byzanteam/jet-actions pull request #72
Opened 2023-12-21 12:21 UTC by YkeLit

- registry login action
- input ALIYUN_SKYLARK_REGISTRY variable
- login registry
- output registry-namespace and registry-hostname

2023-12-22 02:20 UTC, fahchen requested changes
我们应该是要做一个 action 出来登陆多个 registry，不是一个哦

2023-12-22 02:20 UTC, fahchen commented on registry-login/action.yaml
> +description: 'GitHub Action to login image registry'
```suggestion
description: 'Login multiple image registries'
```

2023-12-22 02:20 UTC, fahchen commented on registry-login/action.yaml
> +    description: 'Image registry info. Include registry server address, namespace, username and password.'
给一个例子在这里

2023-12-22 02:20 UTC, fahchen commented on registry-login/src/main.ts
> +export async function main(): Promise<void> {
```suggestion
export async function main(): Promise<void> {

  const inputs: context.Inputs = context.getInputs()
```

2023-12-22 02:20 UTC, fahchen commented on registry-login/src/context.ts
> +}
```suggestion
let inputs: Input | undefined;

export function getInputs(): Inputs {
  if (inputs) return inputs;
  
  const registryInfo = core.getInput('registry-info')
  const [registryHostname, registryNamespace, username, password] =
    registryInfo.split(' ')

  inputs = {
    registryHostname,
    registryNamespace,
    username,
    password
  };
  
  return inputs;
}
```

2023-12-22 08:55 UTC, YkeLit commented
> 我们应该是要做一个 action 出来登陆多个 registry，不是一个哦

我看了下我们之前 https://github.com/Byzanteam/jet-tower/blob/main/.github/workflows/nightly-build.yml 的 workflow，要是登录多个 registry 这个 output 需要再处理一次，相当于输出的一个 key 里面包含多个 values， 然后 values 还要再有个 steps 处理后来使用，这样是可以的吧

2023-12-22 08:59 UTC, fahchen commented
> > 我们应该是要做一个 action 出来登陆多个 registry，不是一个哦
> 
> 我看了下我们之前 https://github.com/Byzanteam/jet-tower/blob/main/.github/workflows/nightly-build.yml 的 workflow，要是登录多个 registry 这个 output 需要再处理一次，相当于输出的一个 key 里面包含多个 values， 然后 values 还要再有个 steps 处理后来使用，这样是可以的吧

可以的
ps. 都在 js 里面实现吧，不做成 composite 的

2023-12-27 07:02 UTC, fahchen commented on registry-login/action.yaml
> +    description: "Image registry info. Each registry should be formatted as follows: ${hostname},${namespace},${username},${password}."
```suggestion
    description: "Image registry info. Each registry should be formatted as follows: `${hostname},${namespace},${username},${password}`."
```

2023-12-27 07:02 UTC, fahchen commented on registry-login/action.yaml
> +    description: 'Image registry namespace.'
可以不要前缀了

```suggestion
  hostname:
    description: 'Image registry hostname.'
  namespace:
    description: 'Image registry namespace.'
```

2023-12-27 07:02 UTC, fahchen commented on registry-login/src/main.ts
> +  await docker.login(inputs.registryHostname, inputs.username, inputs.password)
```suggestion
  await docker.login(inputs.registryHostname, inputs.username, inputs.password)
  context.setOutputs()
```

2023-12-27 07:02 UTC, fahchen commented on registry-login/src/main.ts
> +const inputs: context.Inputs = context.getInputs()
不用在这里缓存，下面直接用就好了，完整代码见下面的评论
```suggestion
const inputs: context.Inputs = context.getInputs()
```

2023-12-27 07:02 UTC, fahchen commented on registry-login/src/main.ts
> +}
```suggestion
export async function main(): Promise<void> {
  const { hostname: registry, username, password } = context.getInputs();
  await docker.login(registry, username, password)
}

async function post(): Promise<void> {
  const { hostname: registry } = context.getInputs();
  
  await docker.logout(registry)
}
```

2023-12-27 07:02 UTC, fahchen commented on registry-login/src/context.ts
> +  registryNamespace: string
可以不用这些前缀了，因为当前的上下文是在一个 registry 中，它里面就隐含有这些信息
```suggestion
  hostname: string
  namespace: string
```

2023-12-27 07:57 UTC, YkeLit commented on registry-login/action.yaml
> +    description: 'Image registry namespace.'
这里 `namespace` 是 typescript 中的一个关键字，看下可以 使用 `repo` 来代替 `namespace` 不

2023-12-27 08:51 UTC, fahchen requested changes

2023-12-27 08:51 UTC, fahchen commented on registry-login/README.md
> +  `ns` - The image registry namespace.
这里还是保持 namespace 吧，js 里面用 ns 就好了
```suggestion
  `namespace` - The image registry namespace.
```

2023-12-27 09:24 UTC, fahchen approved these changes

2023-12-27 09:42 UTC, merged