feat: Define build and deploy action input values
Byzanteam/jet-actions pull request #76
Opened 2024-01-16 10:59 UTC by YkeLit

2024-01-16 11:00 UTC, YkeLit commented on pr-preview/action.yml
> +        echo "${{ inputs.private_key }}" > private.key && chmod 600 private.key
这里，这次可以改成 apiserver 调用，不用 ssh

2024-01-16 16:16 UTC, fahchen commented on pr-preview/action.yml
> +    required: true
这两个可以合并一下

2024-01-16 16:16 UTC, fahchen commented on pr-preview/action.yml
> +    default: ./deploy/values.local.yaml
```suggestion
    default: ./.deploy/values.local.yaml 
```

2024-01-16 16:16 UTC, fahchen commented on pr-preview/action.yml
> +    description: "Release name of the deployment preview"
```suggestion
    description: "Helm release name of the deployment preview"
```

2024-01-16 16:16 UTC, fahchen commented on pr-preview/action.yml
> +    default: 22
这一堆你觉得要不要合并一下呀？一个参数可以输入这三个参数
`user@host:port`

2024-01-16 16:16 UTC, fahchen commented on pr-preview/action.yml
> +    default: "application-chart-template"
这个和上面的相关的 inputs 放一起

2024-01-17 06:12 UTC, YkeLit commented on pr-preview/action.yml
> +    required: true
这里不能合并，之前的登录 action 就是单个仓库登录的，这样做的话还要在 action 里去处理下字符串

2024-01-17 07:03 UTC, fahchen commented on pr-preview/action.yml
> +    required: true
之前做不成多个 registry 的原因是因为 output 不知道怎么输出是吗？

2024-01-17 07:07 UTC, fahchen commented on pr-preview/action.yml
> +    required: true
预览的 image 我们是不是推到一个 registry 就好了呢？

2024-01-17 07:14 UTC, YkeLit commented on pr-preview/action.yml
> +    required: true
可以只推到阿里云去，github 拉取比较麻烦

2024-01-19 07:43 UTC, fahchen requested changes

2024-01-19 07:43 UTC, fahchen commented on pr-preview/action.yml
> +          --namespace test \
在 readme 中加一下这个说明，它最终是部署到我们的哪里了
我希望 readme 里面有一段话，描述了这个 action 做了什么事情，而不用进来看代码

2024-01-19 07:43 UTC, fahchen commented on pr-preview/action.yml
> +    required: true
1. 这里叫 registry 就好了，至于用的时候填那个，填写者决定
2. 这里给一下格式要求

2024-01-19 07:43 UTC, fahchen commented on pr-preview/action.yml
> +    value: ${{ steps.release_name.outputs.release }}
这个有什么使用场景吗？

2024-01-19 07:43 UTC, fahchen commented on pr-preview/action.yml
> +      shell: bash
这个可以设置 defalt
https://docs.github.com/en/actions/using-jobs/setting-default-values-for-jobs

2024-01-19 07:43 UTC, fahchen commented on pr-preview/action.yml
> +        echo "public_url=${{ github.event.pull_request.number }}.${{ steps.release_name.outputs.repo }}.preview.jet.work" >> $GITHUB_OUTPUT
生成的 url 的例子也加到 readme 中说明一下哈

2024-01-19 07:43 UTC, fahchen commented on pr-preview/action.yml
> +        registry-info: ${{ inputs.ali-registry-info }}
这个应该没写完

2024-01-19 07:43 UTC, fahchen commented on pr-preview/action.yml
> +          ${{ steps.acr.outputs.hostname }}/${{ steps.acr.outputs.namespace }}/${{ steps.release_name.outputs.repo }}
把 acr 的关键字换掉哈，我们这里不管 registry

2024-01-19 07:43 UTC, fahchen commented on pr-preview/action.yml
> +          IS_PULL_REQUEST_PREVIEW=true
这两个如何 Dockerfile 里面没有支持就没用哦

2024-01-19 07:48 UTC, fahchen commented on pr-preview/action.yml
> +    default: "application-chart-template"
这个参数我觉得可以设置为完整的值，而不是后半部分
```suggestion
  chart:
    description: "The chart reference, see: https://helm.sh/docs/helm/helm_install/#:~:text=com/charts/nginx-,CHART%20REFERENCES,-A%20chart%20reference"
    required: false
    default: "app-template/application-chart-template"
```

2024-01-19 07:59 UTC, YkeLit commented on pr-preview/action.yml
> +    value: ${{ steps.release_name.outputs.release }}
这里输出给删除的 job 使用，不然删除这个应用要再去算一次

2024-01-19 08:25 UTC, fahchen commented on pr-preview/action.yml
> +    value: ${{ steps.release_name.outputs.release }}
你怎么把这个 output 传到另一个 action 呢？
预览和删除是两个 workflow

2024-01-19 08:50 UTC, YkeLit commented on pr-preview/action.yml
> +    value: ${{ steps.release_name.outputs.release }}
我看了，一个 workflow 可以有多个 jobs。这样的话可以通过 job 来传。
https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow

2024-01-19 08:57 UTC, fahchen commented on pr-preview/action.yml
> +    value: ${{ steps.release_name.outputs.release }}
你理解错了，这里有两个 workflow，不是一个 workflow 的多个 steps

2024-01-19 09:37 UTC, YkeLit commented on pr-preview/action.yml
> +    value: ${{ steps.release_name.outputs.release }}
steps 和 jobs 是两个概念，不过实在拆成两个 workflow 也可以。

2024-01-19 09:38 UTC, fahchen commented on pr-preview/action.yml
> +    value: ${{ steps.release_name.outputs.release }}
这里依然有问题，那里的本质是两个 workflow

2024-01-19 09:49 UTC, YkeLit commented on pr-preview/action.yml
> +    value: ${{ steps.release_name.outputs.release }}
我理解的是这是一个 workflow， 但是里面要完成两个 jobs， 一个是打包部署与评论，另一个是删除。但是这里确实写成一个workflow的话，多次触发会有多个 workflow 等待。所以还是做成两个 workflow吧

2024-01-19 09:50 UTC, YkeLit commented on pr-preview/action.yml
> +          IS_PULL_REQUEST_PREVIEW=true
这里没太懂意思

2024-01-19 11:26 UTC, fahchen commented on pr-preview/action.yml
> +    value: ${{ steps.release_name.outputs.release }}
你理解错了，是两个 workflow
1. 打包，部署，评论
2. 删除

2024-01-19 11:27 UTC, fahchen commented on pr-preview/action.yml
> +          IS_PULL_REQUEST_PREVIEW=true
这两个 build-args 写这里有什么作用？

2024-01-25 08:33 UTC, YkeLit commented on pr-preview/action.yml
> +          IS_PULL_REQUEST_PREVIEW=true
理解错了，已经改到 labels 了

2024-01-25 13:20 UTC, fahchen commented on pr-preview/README.md
> +- 访问地址格式 `pr_number.repo_name.apps.jet.work`
```suggestion
- 访问地址格式 `$pr_number.$repo_name.apps.jet.work`
```

2024-01-26 06:20 UTC, fahchen approved these changes

2024-01-29 02:19 UTC, merged