feat: add and update comment to pull request
Byzanteam/jet-actions pull request #77
Opened 2024-01-18 07:21 UTC by YkeLit

- input a message
- printed to pull request comment

2024-01-18 09:19 UTC, fahchen requested changes

2024-01-18 09:19 UTC, fahchen commented on comment-pull-request/src/main.ts
> +    const body = `预览地址：${message}\n${comment_tag_pattern}`
```suggestion
    const body = `${message}\n${comment_tag_pattern}`
```

2024-01-18 09:19 UTC, fahchen commented on comment-pull-request/README.md
> +    message: "Some messages printed in pull request"
```suggestion
    body: "The comment body"
```

2024-01-18 09:19 UTC, fahchen commented on comment-pull-request/README.md
这个 action 的名字和干的事情不一致，因为如果只是 comment，不应该有删除旧的 comment 的行为

2024-01-19 07:51 UTC, fahchen requested changes

2024-01-19 07:51 UTC, fahchen commented on pr-comment-operation/README.md
> +- name: Login registry
name 不太对

2024-01-19 07:51 UTC, fahchen commented on pr-comment-operation/README.md
> +    body: "Some messages printed in pull request"
不用 print 这个词，不合适

2024-01-19 07:51 UTC, fahchen commented on pr-comment-operation/src/main.ts
> +    const comment_tag_pattern = `<!-- COMMENT GENERATED BY ACTIONS -->`
```suggestion
    const comment_tag_pattern = `<!-- COMMENT GENERATED BY PR-COMMENT-OPERATION ACTIONS -->`
```

2024-01-19 07:51 UTC, fahchen commented on pr-comment-operation/README.md
readme 说一下这个 action 做了什么事情

2024-01-25 12:11 UTC, fahchen reviewed
代码没问题了，但这个名字和描述感觉还是不准确

2024-01-25 14:22 UTC, YkeLit commented
> 代码没问题了，但这个名字和描述感觉还是不准确

Ok 我在推敲一下

2024-01-31 14:37 UTC, fahchen approved these changes

2024-02-01 02:23 UTC, merged