chore: added the ability to use .tool-versions file to set the version
Byzanteam/jet-actions pull request #99
Opened 2024-09-20 07:37 UTC by danewalters

2024-09-20 07:42 UTC, danewalters commented on setup-elixir/action.yml
> +    required: false
这里需不需要设置一个默认版本哇 @fahchen

2024-09-20 07:42 UTC, danewalters commented on setup-elixir/action.yml
> +    required: false
required 为 false，string 类型不设置默认是一个空字符串

2024-09-20 07:52 UTC, fahchen requested changes

2024-09-20 07:52 UTC, fahchen commented on setup-elixir/action.yml
> +  use-tool-versions:
保持一致
```suggestion
  tool-versions:
```

2024-09-20 07:52 UTC, fahchen commented on setup-elixir/action.yml
> +    required: false
不用给默认值

2024-09-20 07:52 UTC, fahchen commented on setup-elixir/action.yml
> +        version-file: '.tool-versions'
https://github.com/erlef/setup-beam?tab=readme-ov-file#version-file
测试下，把成功的 run 贴一下
```suggestion
        version-file: '.tool-versions'
        version-type: strict
```

2024-09-20 07:52 UTC, fahchen commented on setup-elixir/action.yml
>          elixir-version: ${{ inputs.elixir-version }}
你试试看这两步能不能合并到一起？
```
      - uses: erlef/setup-beam@v1
        with:
          version-file: ${{ inputs.version-file }}
          version-type: strict
          otp-version: ${{ inputs.otp-version }}
          elixir-version: ${{ inputs.elixir-version }}
```

2024-09-22 09:57 UTC, danewalters commented on setup-elixir/action.yml
> +        version-file: '.tool-versions'
https://github.com/Byzanteam/jet-storage-plugin/actions/runs/10980131585

2024-09-22 14:52 UTC, fahchen requested changes

2024-09-22 14:52 UTC, fahchen commented on setup-elixir/action.yml
> +        version-type: ${{ inputs.tool-versions == 'true' && 'strict' || 'range' }}
https://github.com/Byzanteam/jet-actions/pull/99#discussion_r1768153018

2024-09-23 01:36 UTC, danewalters commented on setup-elixir/action.yml
> +        version-type: ${{ inputs.tool-versions == 'true' && 'strict' || 'range' }}
https://github.com/Byzanteam/jet-storage-plugin/actions/runs/10986180757

2024-09-23 02:02 UTC, fahchen requested changes

2024-09-23 02:02 UTC, fahchen commented on setup-elixir/action.yml
> +    default: ".tool-versions"
不要给 defalt，给了 default 下面两个参数就没用了

2024-09-23 02:03 UTC, fahchen commented on setup-elixir/action.yml
> +    default: ".tool-versions"
给一下这两个的测试结果：
1. 填 version-file 
2. 填 otp，elixir version 的

2024-09-23 02:42 UTC, danewalters commented on setup-elixir/action.yml
> +    default: ".tool-versions"
ok

2024-09-23 02:58 UTC, danewalters commented on setup-elixir/action.yml
> +    default: ".tool-versions"
已经改了

2024-09-23 03:08 UTC, danewalters commented on setup-elixir/action.yml
> +    default: ".tool-versions"
https://github.com/Byzanteam/jet-storage-plugin/actions/runs/10986180757/job/30500961824

2024-09-23 04:10 UTC, danewalters commented on setup-elixir/action.yml
> +    default: ".tool-versions"
https://github.com/Byzanteam/jet-storage-plugin/actions/runs/10987400381/workflow

2024-09-23 04:21 UTC, danewalters commented on setup-elixir/action.yml
> +    default: ".tool-versions"
https://github.com/Byzanteam/jet-storage-plugin/actions/runs/10987585715/workflow

2024-09-23 04:36 UTC, fahchen approved these changes

2024-09-24 01:48 UTC, vanppo approved these changes

2024-09-24 02:02 UTC, YkeLit approved these changes

2024-09-24 02:36 UTC, merged